spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL:localhost}:3306/twitch?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:admin111}
  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: classpath:database-init.sql
  cache:
    caffeine:
      spec: expireAfterWrite=1m

twitch:
  client-id: "y2hygtk76tkbgjyfrwvo9whfd6oaux"
  secret: "d21jmjub8fpyvjm7lm4ref0ez6wn0v"

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming http requests
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE # Outgoing http requests
    org.springframework.jdbc.core: DEBUG # SQL
